#!/bin/bash

python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_1.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_1.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_2.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_2.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_3.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_3.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_4.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_4.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_5.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_5.tsv & 
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_6.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_6.tsv &
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_7.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_7.tsv &
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_8.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_8.tsv &
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_9.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_9.tsv &
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_10.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_10.tsv &
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_11.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_11.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_12.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_12.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_13.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_13.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_14.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_14.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_15.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_15.tsv & 
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_16.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_16.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_17.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_17.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_18.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_18.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_19.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_19.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_20.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_20.tsv & 
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_21.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_21.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_22.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_22.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_23.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_23.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_24.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_24.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_25.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_25.tsv & 
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_26.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_26.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_27.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_27.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_28.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_28.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_29.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_29.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_30.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_30.tsv & 
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_31.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_31.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_32.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_32.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_33.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_33.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_34.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_34.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_35.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_35.tsv & 
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_36.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_36.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_37.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_37.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_38.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_38.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_39.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_39.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_40.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_40.tsv & 
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_41.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_41.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_42.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_42.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_43.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_43.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_44.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_44.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_45.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_45.tsv & 
wait
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_46.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_46.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_47.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_47.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_48.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_48.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_49.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_49.tsv & 
python main_random_rules.py --min_span_length 1 --max_span_length 15 --num_matches 3 --rule_type enhanced_syntax     --save_path "random/enhanced_syntax_50.jsonl"     --fields_word_weight 1 --fields_lemma_weight 0 --fields_tag_weight 0     --data_paths         /home/rvacareanu/new__projects/odinson/231109_data2_50.tsv & 
wait
